[toolchain]
# Please, from time to time, update this to the latest stable version on Rust Forge: https://forge.rust-lang.org/
channel = "1.71.0"
components = ["rustfmt", "clippy"]
targets = [ "wasm32-unknown-unknown"]
